export const LIKE_FILM_DETAIL = 'LIKE_FILM_DETAIL';
export const FETCH_LIKE_FILM = 'FETCH_LIKE_FILM';

export const FETCH_LIKE_FILM_SUCCEEDED = 'FETCH_LIKE_FILM_SUCCEEDED';
export const FETCH_LIKE_FILM_FAILED = 'FETCH_LIKE_FILM_FAILED';
