export const LIKE_FILM = 'LIKE_FILM';
export const XEM_FILM = 'XEM_FILM';
export const FETCH_FILM = 'FETCH_FILM';
export const FETCH_LIST_LIKE = 'FETCH_LIST_LIKE';
export const LOGOUT = 'LOGOUT';
export const FETCH_INFO_USER = 'FETCH_INFO_USER';
export const FETCH_USER_LOCAL = 'FETCH_USER_LOCAL';
export const ADD_COUNT_VIEW = 'ADD_COUNT_VIEW';


export const FETCH_FILM_SUCCEEDED = 'FETCH_FILM_SUCCEEDED';
export const FETCH_FILM_FAILED = 'FETCH_FILM_FAILED';
export const LIKE_FILM_SUCCEEDED = 'LIKE_FILM_SUCCEEDED';
export const LIKE_FILM_FAILED = 'LIKE_FILM_FAILED';
export const FETCH_LIST_LIKE_SUCCEEDED = 'FETCH_LIST_LIKE_SUCCEEDED';
export const FETCH_LIST_LIKE_FAILED = 'FETCH_LIST_LIKE_FAILED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const FETCH_INFO_USER_SUCCEEDED = 'FETCH_INFO_USER_SUCCEEDED';
export const FETCH_INFO_USER_FAILED = 'FETCH_INFO_USER_FAILED';
export const FETCH_USER_LOCAL_SUCCEEDED = 'FETCH_USER_LOCAL_SUCCEEDED';
export const FETCH_USER_LOCAL_FAILED = 'FETCH_USER_LOCAL_FAILED';
