export const LIKE_FILM = 'LIKE_FILM'
export const XEM_FILM = 'XEM_FILM'
export const FETCH_FILM = 'FETCH_FILM'
export const FETCH_LIST_LIKE ='FETCH_LIST_LIKE'


export const FETCH_FILM_SUCCEEDED = 'FETCH_FILM_SUCCEEDED'
export const FETCH_FILM_FAILED = 'FETCH_FILM_FAILED'
export const LIKE_FILM_SUCCEEDED ='LIKE_FILM_SUCCEEDED'
export const LIKE_FILM_FAILED = 'LIKE_FILM_FAILED'
export const FETCH_LIST_LIKE_SUCCEEDED = 'FETCH_LIST_LIKE_SUCCEEDED'
export const FETCH_LIST_LIKE_FAILED ='FETCH_LIST_LIKE_FAILED'